debug: false
uuid: 2be95097-78b4-4157-b91a-5342466aa183
token_id: 9BvrbeRboGVDd2nM
token: Fh7b7vlltcFllSaXCb8TKyckT7BWCD7jpZtaSVRTNJnMjrNs13Rp1iEA8x93lYM6
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/improved.rationally-duck.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/improved.rationally-duck.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://redesigned-space-robot-v6rpjxp5rgqwhppg7-80.app.github.dev'
